### PR TITLE
Add `--version` option feature

### PR DESCRIPTION
**Pull request by yaegassy**
## Description

Hi. Thank you for creating a wonderful language server.

By the way, I have added a `--version` option to the `djlsp` (`django-template-lsp`) command.

## Screen shot

djlsp-add-version-option

### CODE REVIEW

**Comment by krukas** [comment]
Thanks for the contribution

**Comment by yaegassy** [comment]
@krukas Thank you for merging the pull request. By the way, I have some ideas for additional features, not feature requests.

It might not be possible to retrieve document information for tags and filters with the parser. However, if you can provide document information, I believe it would be possible to implement `COMPLETION_ITEM_RESOLVE` and `HOVER`.

- COMPLETION_ITEM_RESOLVE (e.g. jedi-language-server)
  - https://github.com/pappasam/jedi-language-server/blob/9df0ab5c3481c4e637a8cc1dc3bb5e7afb11c960/jedi_language_server/server.py#L184-L192
- HOVER
  - https://pygls.readthedocs.io/en/latest/examples/hover.html

**Comment by yaegassy** [comment]
Currently, I think the `django_settings_module` needs to be explicitly set for each project.

If the language server is creating an index for the entire project at startup, it would be very convenient if it could be auto-detected.

**Comment by krukas** [comment]
@yaegassy I have added issues for your suggestions. We already have an index for the whole project: https://github.com/fourdigits/django-template-lsp/blob/main/djlsp/index.py this is indexed/collected with: https://github.com/fourdigits/django-template-lsp/blob/main/djlsp/scripts/django-collector.py

**Pull request merged**
